### ISSUE TITLE
Support Psych v4.0.0

### ISSUE THREAD

**Issue by tmimura39** [settingslogic/settingslogic#20]
Ruby master ships with Psych 4.0.0 which makes `YAML.load`
defaults to safe mode (https://github.com/ruby/psych/pull/487).

So `alias` is not available.

```yaml
# application.yml
defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
```
```ruby
# main.rb
require 'settingslogic'

class Settings < Settingslogic
  source 'application.yml'
  namespace 'development'
end

p Psych::VERSION
p Settings.neat_setting
```
```bash
root@a250c88f3eb5:~# ruby main.rb
"4.0.1"
/usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: defaults (Psych::BadAlias)
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:30:in `visit'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych.rb:335:in `safe_load'
	from /usr/local/bundle/gems/psych-4.0.1/lib/psych.rb:370:in `load'
	from /usr/local/bundle/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
	from /usr/local/bundle/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
	from /usr/local/bundle/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
	from /usr/local/bundle/gems/settingslogic-2.0.9/lib/settingslogic.rb:66:in `method_missing'
	from main.rb:9:in `<main>'
```

**Comment by lionelchauvin** [comment]
@goosetav Hello, we are using this gem in our projects and we have the same problem with ruby 3. Can this pull request be reviewed ?

**Comment by amy-hs** [comment]
@binarylogic @goosetav Bumping! This would be really, really helpful to update.

**Comment by ccurtisj** [comment]
Same ❤️

**Comment by odarriba** [comment]
is there any fork that is maintained and with this issue fixed?
